<a href="https://colab.research.google.com/github/AjMing/Pattern-EGCI463/blob/main/Week7-8/Simple_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
X = np.array([  [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])

# The third value is the threshold value

In [ ]:
y = np.array([[0,1,1,1]]).T #OR function

In [ ]:
l0=X

# just changing the name


In [ ]:
print(l0)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [ ]:
def sigmoid(x,deriv=False):

	if(deriv==True):
		return x*(1-x) #return this when derivative = true
	return 1/(1+np.exp(-x)) #return this when derivative = false

In [ ]:
np.random.seed(1)   #1 is the random weight
       # initialize weights randomly with mean 0
w0 = 2*np.random.random((3,1)) - 1 #make random values between -1 and 1
w1 = 2*np.random.random((3,1)) - 1
w2 = 2*np.random.random((3,1)) - 1

print(w0)
print(w1)
print(w2)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
[[-0.39533485]
 [-0.70648822]
 [-0.81532281]]
[[-0.62747958]
 [-0.30887855]
 [-0.20646505]]


In [ ]:
# Demonstrating 1 single round to use in the next cell

l1=sigmoid(np.dot(l0,w0)) #feed forward/ predict the output
l2=sigmoid(np.dot(l0,w1))

# Hidden layer
o = np.concatenate((l1, l2), axis=1)
o = np.concatenate((o, [[1], [1], [1], [1]]), axis=1)

# Output layer
l3 = sigmoid(np.dot(o,w2))

print(l1)
print(l2)
print(l3)

[[0.2689864 ]
 [0.36375058]
 [0.23762817]
 [0.3262757 ]]
[[0.3067574 ]
 [0.17919499]
 [0.22958471]
 [0.12818018]]
[[0.38461641]
 [0.37987929]
 [0.39496583]
 [0.38917331]]


In [ ]:
learning_rate = 0.2

for iter in range(20): #setting the max iteration
    l1=sigmoid(np.dot(l0,w0))
    l2=sigmoid(np.dot(l0,w1))
    #feed forward/ predict the output.
    # np.dot(l0,w0) would multiple the input with weight and sum all.
    # sigmoid() would bring the value between 0 and 1 (sigmoid function).

    # Hidden layer
    o = np.concatenate((l1, l2), axis=1)
    o = np.concatenate((o, [[1], [1], [1], [1]]), axis=1)

    # Output layer
    l3 = sigmoid(np.dot(o,w2))


    print(l1)
    print(l2)
    print(l3)

    # Finding error
    l3_error = l3 - y

    lH_error = np.dot(l3_error,w2.T)
    l2_error = lH_error[:,[1]]
    l1_error = lH_error[:,[0]]

    # Finding delta
    l3_delta = l3_error*sigmoid(l3,True)
    l2_delta = l2_error*sigmoid(l2,True)
    l1_delta = l1_error*sigmoid(l1,True)

    # Adjusting the weight
    w2 -= np.dot(o.T, l3_delta)
    w0 -= np.dot(l0.T, l1_delta)
    w1 -= np.dot(l0.T, l2_delta)

    s3='Round '+ str(iter)+' has error'+ str(sum(lH_error**2))+' as lH error'
    print(s3)

    print(l1)
    print(l2)
    print(l3)

    if(sum(l3_error**2)<=0.008): break

    # If the error reduces at every round, its a good sign

[[0.40690175]
 [0.15779702]
 [0.12214053]
 [0.03660645]]
[[0.66122699]
 [0.15829639]
 [0.17716868]
 [0.02032489]]
[[0.46550854]
 [0.72975906]
 [0.73110663]
 [0.79604219]]
Round 0 has error[0.48449082 1.17657128 0.83295876] as lH error
[[0.40690175]
 [0.15779702]
 [0.12214053]
 [0.03660645]]
[[0.66122699]
 [0.15829639]
 [0.17716868]
 [0.02032489]]
[[0.46550854]
 [0.72975906]
 [0.73110663]
 [0.79604219]]
[[0.41762715]
 [0.15740384]
 [0.12265597]
 [0.03513918]]
[[0.67072515]
 [0.15490098]
 [0.17267178]
 [0.01843417]]
[[0.45149079]
 [0.73286094]
 [0.7343804 ]
 [0.80025031]]
Round 1 has error[0.48953209 1.20201793 0.82206734] as lH error
[[0.41762715]
 [0.15740384]
 [0.12265597]
 [0.03513918]]
[[0.67072515]
 [0.15490098]
 [0.17267178]
 [0.01843417]]
[[0.45149079]
 [0.73286094]
 [0.7343804 ]
 [0.80025031]]
[[0.42835725]
 [0.15692933]
 [0.12310124]
 [0.03369653]]
[[0.6797003 ]
 [0.15137485]
 [0.16808619]
 [0.01670001]]
[[0.43767344]
 [0.73626275]
 [0.73794847]
 [0.80451827]]
Round 2 has error

In [ ]:
# YOU CAN KEEP ADJUSTTING THE LEARNING RATE AND RANDOM SEED TO HAVE THE BEST RESULT IN THE SMALLEST NUMBER OF ROUNDS